JinxiaocunApp/Models/BDepartment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace JinxiaocunApp.Models
{
    public class BDepartment
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BID { get; set; }

        [Required]
        [Display(Name="部门编码")]
        [Remote("IsExist", "RemoteAttr", AdditionalFields = "BID", ErrorMessage = "部门编码 重复")]
        public string BNumber { get; set; }

        [Required]
        [Display(Name = "部门全称")]
        [Remote("IsExist", "RemoteAttr",AdditionalFields="BID", ErrorMessage = "部门全称 重复")]
        public string BFullName { get; set; }

        [Display(Name = "部门简称")]
        public string BSmallName { get; set; }

        [Display(Name = "拼音码")]
        public string BPinyin { get; set; }

        [Display(Name="备注")]
        [DataType(DataType.Text)]
        public string BRemark { get; set; }

        //public List<BEmplyee> bemplyee { get; set; }
    }
}

JinxiaocunApp/Controllers/BDepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JinxiaocunApp.Models;
using JinxiaocunApp.Filters;
using JinxiaocunApp.Extensions;

namespace JinxiaocunApp.Controllers
{
    public class BDepartmentController : Controller
    {
        private JinxiaocunAppContext db = new JinxiaocunAppContext();

        private int PageSize = 10;
        //
        // GET: /Default1/

        [MultipleResponseFormats]
        public ActionResult Index(string id = "")
        {
            ViewBag.SuperRef = id;
            ViewBag.PageDiv = Guid.NewGuid().ToString();
            ViewBag.Pagination = Guid.NewGuid().ToString();

            if (ViewBag.PageSize == null)
            { 
                ViewBag.PageSize = PageSize;
                ViewBag.CurrentPage = 1;
                ViewBag.TotalRecord = db.BDepartments.Count();
                ViewBag.TotalPage =Math.Ceiling( ViewBag.TotalRecord / (double)ViewBag.PageSize);
                
            }


            return View(db.BDepartments.Where(m => m.BID == 1));
        }

        public ActionResult Pages(int id=1,string SuperRef="")
        {
            ViewBag.SuperRef=SuperRef;
            ViewBag.CurrentPage = id;
            
            ViewBag.tid = id+"  "+new Random().Next();
            return PartialView(db.BDepartments.OrderBy(m=>m.BID).Skip((id-1) * PageSize).Take(PageSize).ToList());
            //return PartialView(db.BDepartments.ToList());
        }

        [MultipleResponseFormats]
        public ActionResult PartialIndex()
        {
            return View(db.BDepartments.ToList());
        }

        //
        // GET: /Default1/Details/5

        [MultipleResponseFormats]
        public ActionResult Details(int id = 0)
        {
            BDepartment bdepartment = db.BDepartments.Find(id);
            if (bdepartment == null)
            {
                return HttpNotFound();
            }
            return View(bdepartment);
        }

        //
        // GET: /Default1/Create

        [MultipleResponseFormats]
        public ActionResult Create()
        {

            if (db.BDepartments.Count() <= 0)
            {
                return View();
            }
           

            return View(new BDepartment { BNumber = db.BDepartments.OrderByDescending(m => m.BID).First().BNumber.GetAscNumberStr() });
            
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        [MultipleResponseFormats]
        public ActionResult Create(BDepartment bdepartment)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    //if (db.BDepartments.Find(bdepartment.BNumber) != null)
                    //{
                    //    return RedirectToAction("Error", "MyTart", new { err = "编号不能重复", Act = "Create", Con = "BDepartment" });

                    //}
                    db.BDepartments.Add(bdepartment);
                    
                    db.SaveChanges();

                    return RedirectToAction("Create");
                    //return View(new BDepartment { BNumber = bdepartment.BNumber.GetAscNumberStr() });
                }
                return View(bdepartment);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            

            //return View(bdepartment);
        }

        //
        // GET: /Default1/Edit/5

        [MultipleResponseFormats]
        public ActionResult Edit(int id = 0,string SuperRef="")
        {
            ViewBag.SuperRef=SuperRef;
            BDepartment bdepartment = db.BDepartments.Find(id);
            if (bdepartment == null)
            {
                return HttpNotFound();
            }
            return View(bdepartment);
            //return View(bdepartment);
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        [MultipleResponseFormats]
        public ActionResult Edit(BDepartment bdepartment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bdepartment).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
            }
            return View(bdepartment);
        }

        //
        // GET: /Default1/Delete/5

        [MultipleResponseFormats]
        public ActionResult Delete(int id =0)
        {
            BDepartment bdepartment = db.BDepartments.Find(id);
            if (bdepartment == null)
            {
                return HttpNotFound();
            }
            return View(bdepartment);
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost, ActionName("Delete")]
        [MultipleResponseFormats]
        public ActionResult DeleteConfirmed(int id = 0)
        {
            BDepartment bdepartment = db.BDepartments.Find(id);
            db.BDepartments.Remove(bdepartment);
            db.SaveChanges();

            return Content("删除成功");
            //return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

JinxiaocunApp/Controllers/MyTartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JinxiaocunApp.Filters;

namespace JinxiaocunApp.Controllers
{
    
    public class MyTartController : Controller
    {
        //
        // GET: /MyTart/

        JinxiaocunApp.Models.JinxiaocunAppContext db = new Models.JinxiaocunAppContext();
        [MultipleResponseFormats]
        public ActionResult Index()
        {
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult Error(string err="错误",string Act="index",string Con="Home")
        {
            ViewBag.err = err;
            ViewBag.Act = Act;
            ViewBag.Con = Con;
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult MenuPartial(string id="id",string tabName="新Tab",int tabid=-99)
        {
            ViewBag.divid = id;
            ViewBag.name = tabName;
            if(tabid!=-99)
            ViewBag.MenuM = db.BPartMenus.Where(m => m.BParentID == tabid).ToList();
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult PaginationPartial(string id = "Paginationid", int TotalPage = 10, string tbodyPages = "", string ControllerName="")
        {
            ViewBag.divid = id;
            ViewBag.TotalPage = TotalPage==0?1:TotalPage;
            ViewBag.tbodyPages = tbodyPages;
            ViewBag.ControllerName = ControllerName;
            return View();
        }

        public ActionResult Part1()
        {
            return PartialView();
        }

        public ActionResult Part2()
        {
            return PartialView();
        }

        public ActionResult SystemM()
        {
            return PartialView();
        }

        [MultipleResponseFormats]
        public ActionResult IndexM()
        {
            return View();
        }

        public ActionResult Part3()
        {
            return Content("建设中...");
        }
        public ActionResult Part4()
        {
            return Content("Part4"+Request["aa"]+Request["bb"]);
        }
        public ActionResult Part5()
        {
            return Content("<div>Part5</div>");
        }
    }
}

JinxiaocunApp/Views/BDepartment/Create.cshtml
@model JinxiaocunApp.Models.BDepartment

@{
    ViewBag.Title = "Create";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (1 == 2)
    { 
        <script type="text/javascript" src="../../Scripts/jquery-2.0.3-vsdoc.js"></script>
    }

@using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnSuccess = "onReload('/bdepartment/index')"}))
{
@*@using (Html.BeginForm()) {*@
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BDepartment</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.BNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BNumber)
            @Html.ValidationMessageFor(model => model.BNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BFullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BFullName)
            @Html.ValidationMessageFor(model => model.BFullName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BSmallName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BSmallName)
            @Html.ValidationMessageFor(model => model.BSmallName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BPinyin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BPinyin)
            @Html.ValidationMessageFor(model => model.BPinyin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BRemark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BRemark)
            @Html.ValidationMessageFor(model => model.BRemark)
        </div>

        <p>
            <input type="submit" value="创建" />
        </p>
    </fieldset>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>
    <script>
        $.getScript("/Scripts/jquery.validate.unobtrusive.js");
        $(function () {
            PinyinAutoGen("BFullName", "BSmallName");
            PinyinAutoGen("BFullName", "BPinyin");
        });

    </script>
@*@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
}*@

JinxiaocunApp/Views/BDepartment/Delete.cshtml
@model JinxiaocunApp.Models.BDepartment

@{
    ViewBag.Title = "删除";
}

<h2>删除</h2>

<h3>你确定要删除吗？</h3>
<fieldset>
    <legend>部门</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BFullName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BFullName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BSmallName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BSmallName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BPinyin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BPinyin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BRemark)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BRemark)
    </div>
</fieldset>
@using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnComplete = "onReloadClose('/bdepartment/index')" })){
    <p>
        <input type="submit" value="Delete" /> |
       @* @Html.ActionLink("Back to List", "Index")*@
    </p>
}

JinxiaocunApp/Views/BDepartment/Details.cshtml
@model JinxiaocunApp.Models.BDepartment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>BDepartment</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BFullName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BFullName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BSmallName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BSmallName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BPinyin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BPinyin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BRemark)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BRemark)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.BID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JinxiaocunApp/Views/BDepartment/Edit.cshtml
@model JinxiaocunApp.Models.BDepartment

@{
    ViewBag.Title = "编辑";
}

@using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnComplete = "onReloadClose('/bdepartment/index')" }))
{
@*@using (Html.BeginForm()) {*@
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BDepartment</legend>

        @Html.HiddenFor(model => model.BID)

        <div class="editor-label">
            @Html.LabelFor(model => model.BNumber)
        </div>
        <div class="editor-field">
            
            @Html.EditorFor(model => model.BNumber)
            @Html.ValidationMessageFor(model => model.BNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BFullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BFullName)
            @Html.ValidationMessageFor(model => model.BFullName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BSmallName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BSmallName)
            @Html.ValidationMessageFor(model => model.BSmallName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BPinyin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BPinyin)
            @Html.ValidationMessageFor(model => model.BPinyin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BRemark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BRemark)
            @Html.ValidationMessageFor(model => model.BRemark)
        </div>

        <p>
            <input type="submit" value="保存" />
        </p>
    </fieldset>
}

<script>
    $.getScript("/Scripts/jquery.validate.unobtrusive.js");
    $(function () {
        PinyinAutoGen("BFullName", "BSmallName");
        PinyinAutoGen("BFullName", "BPinyin");
    });
    </script>
@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

JinxiaocunApp/Views/BDepartment/Index.cshtml
@model IEnumerable<JinxiaocunApp.Models.BDepartment>
@{
    ViewBag.Title = "Index";
}
<div class="panel panel-info">
   @* <div class="panel-heading">
        部门管理</div>*@
    @if (1 == 2)
    { 
        <script type="text/javascript" src="../../Scripts/jquery-2.0.3-vsdoc.js"></script>
    }
   
    
    <p>
        @Ajax.ActionLink("新建", "Create", new { id = ViewBag.SuperRef }, new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showW('部门信息-新建')" }, new { @class="btn"})
    </p>
    <table class="table-striped table-hover table-bordered" width="100%">
        <tr class="alert-info">
            <th>
                @Html.DisplayNameFor(model => model.BNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BSmallName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BPinyin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BRemark)
            </th>
            <th>
            </th>
        </tr>
        <tbody id="@ViewBag.PageDiv">
            @Html.Action("Pages", "BDepartment", new { SuperRef = ViewBag.SuperRef })
        </tbody>
    </table>
    @Html.Action("PaginationPartial", "MyTart", new { id = ViewBag.Pagination, TotalPage = ViewBag.TotalPage, tbodyPages = ViewBag.PageDiv, ControllerName = "BDepartment" })
</div>

JinxiaocunApp/Views/BDepartment/Pages.cshtml
@model IEnumerable<JinxiaocunApp.Models.BDepartment>

@foreach (var item in Model)
{
    <tr ondblclick="LoadShow('/BDepartment/Edit/@item.BNumber');">
        <td>
            @Html.DisplayFor(modelItem => item.BNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BFullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BSmallName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BPinyin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BRemark)
        </td>
        <td>
            @Ajax.ActionLink("编辑", "Edit", new { id = item.BID, SuperRef = ViewBag.SuperRef }, new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showW('部门信息-编辑')" })
            |
            @Ajax.ActionLink("查看", "Details", new { id = item.BID }, new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showW('部门信息-查看')" })
            |
            @Ajax.ActionLink("删除", "Delete", new { id = item.BID }, new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showW('部门信息-删除')" })

        </td>
    </tr>
}