JinxiaocunApp/Controllers/BPartMenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JinxiaocunApp.Models;
using JinxiaocunApp.Filters;

namespace JinxiaocunApp.Controllers
{
    public class BPartMenuController : Controller
    {
        private JinxiaocunAppContext db = new JinxiaocunAppContext();

        //
        // GET: /BPartMenu/

        [MultipleResponseFormats]
        public ActionResult Index()
        {
            return View(db.BPartMenus.ToList());
        }

        public ActionResult Menu(int id = 0, string tagetdiv="")
        {
            ViewBag.Bid = id;
            ViewBag.divid = Guid.NewGuid().ToString();
            //ViewBag.tagetdiv = Request["tagetdiv"]??"tabs-2";
            ViewBag.tagetdiv = tagetdiv;
            return PartialView(db.BPartMenus.ToList());
        }
        //
        // GET: /BPartMenu/Details/5

        public ActionResult Details(int id = 0)
        {
            BPartMenu bpartmenu = db.BPartMenus.Find(id);
            if (bpartmenu == null)
            {
                return HttpNotFound();
            }
            return View(bpartmenu);
        }

        //
        // GET: /BPartMenu/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /BPartMenu/Create

        [HttpPost]
        public ActionResult Create(BPartMenu bpartmenu)
        {
            if (ModelState.IsValid)
            {
                db.BPartMenus.Add(bpartmenu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bpartmenu);
        }

        //
        // GET: /BPartMenu/Edit/5

        public ActionResult Edit(int id = 0)
        {
            BPartMenu bpartmenu = db.BPartMenus.Find(id);
            if (bpartmenu == null)
            {
                return HttpNotFound();
            }
            return View(bpartmenu);
        }

        //
        // POST: /BPartMenu/Edit/5

        [HttpPost]
        public ActionResult Edit(BPartMenu bpartmenu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bpartmenu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bpartmenu);
        }

        //
        // GET: /BPartMenu/Delete/5

        public ActionResult Delete(int id = 0)
        {
            BPartMenu bpartmenu = db.BPartMenus.Find(id);
            if (bpartmenu == null)
            {
                return HttpNotFound();
            }
            return View(bpartmenu);
        }

        //
        // POST: /BPartMenu/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BPartMenu bpartmenu = db.BPartMenus.Find(id);
            db.BPartMenus.Remove(bpartmenu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

JinxiaocunApp/Controllers/MyTartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JinxiaocunApp.Filters;

namespace JinxiaocunApp.Controllers
{
    
    public class MyTartController : Controller
    {
        //
        // GET: /MyTart/

        JinxiaocunApp.Models.JinxiaocunAppContext db = new Models.JinxiaocunAppContext();
        [MultipleResponseFormats]
        public ActionResult Index()
        {
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult Error(string err="错误",string Act="index",string Con="Home")
        {
            ViewBag.err = err;
            ViewBag.Act = Act;
            ViewBag.Con = Con;
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult MenuPartial(string id="id",string tabName="新Tab",int tabid=-99)
        {
            ViewBag.divid = id;
            ViewBag.name = tabName;
            if(tabid!=-99)
            ViewBag.MenuM = db.BPartMenus.Where(m => m.BParentID == tabid).ToList();
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult PaginationPartial(string id = "Paginationid", int TotalPage = 10, string tbodyPages = "", string ControllerName="")
        {
            ViewBag.divid = id;
            ViewBag.TotalPage = TotalPage==0?1:TotalPage;
            ViewBag.tbodyPages = tbodyPages;
            ViewBag.ControllerName = ControllerName;
            return View();
        }

        public ActionResult Part1()
        {
            return PartialView();
        }

        public ActionResult Part2()
        {
            return PartialView();
        }

        public ActionResult SystemM()
        {
            return PartialView();
        }

        [MultipleResponseFormats]
        public ActionResult IndexM()
        {
            return View();
        }

        public ActionResult Part3()
        {
            return Content("建设中...");
        }
        public ActionResult Part4()
        {
            return Content("Part4"+Request["aa"]+Request["bb"]);
        }
        public ActionResult Part5()
        {
            return Content("<div>Part5</div>");
        }
    }
}

JinxiaocunApp/Views/MyTart/Index.cshtml
<div class="col-md-6 col-lg-6">
    <div class="row">
        <div class="panel panel-info" >
            <div class="panel-headings">
                <span>
                    <img src="~/Images/news/ak15.jpg"></img>
                </span>
                <span>
                    <strong>通知公告</strong>
                </span>
                <button id="indexBtnTZ" name='@Url.Content("~/Tender_TongZhi/MoreIndex/1")' style="float:right;" class="btn btn-link" onclick='AddShowDivN(this, $(this).attr("name"));'>更多>></button>
            </div>
            <div class="panel-body" style="min-height:133px;">
                @Html.Action("IndexTop", "Tender_TongZhi")
            </div>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-info" style="height:243px">
            <div class="panel-headings">
                <span>
                    <img src="~/Images/news/ak15.jpg"></img>
                </span>
                <span>
                    <strong>历史招标</strong>
                </span>
                <button id="indexBtnL" name='@Url.Content("~/Tender_GongGao/Index")' style="float:right;" class="btn btn-link" onclick='AddShowDivN(this, $(this).attr("name"));'>更多>></button>
            </div>
            <div class="panel-body">
                @Html.Action("TopIndex", "Tender_GongGao", new { id=1})
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 col-lg-6" style="padding-right:0px;">
    <div class="panel panel-info" style="height:427px">
        <div class="panel-headings">
            <span>
                <img src="~/Images/news/ak15.jpg"></img>
            </span>
            <span>
                <strong>招标信息</strong>
            </span>
            <button id="indexBtnN" name='@Url.Content("~/Tender_GongGao/Index/1")' style="float:right;" class="btn btn-link" onclick='AddShowDivN(this, $(this).attr("name"));'>更多>></button>
        </div>
        <div class="panel-body">
           @Html.Action("TopIndex", "Tender_GongGao")
        </div>
    </div>
</div>

JinxiaocunApp/Views/MyTart/IndexM.cshtml
@*这不是页面 只是一个部分视图，不能用@section*@
     <div  class="col-lg-12" id="indexHeader">
            <div id="logo" class="float-left logo">
            <h1>LOGO</h1>
            
            </div>
            <div id="header-right">
                    @Html.Partial("_LoginPartial")
            </div>
    </div>
 
<div style="width: 100%; height: 100%;">
    
    <div class="systemList" style="height: 160px;">
        <ul>
            <li>
                <img alt="新手帮助" src="http://erp.mygjp.com/Images/menuImg/新手帮助.png" href="ROSMain.gspx" />
                <span>新手帮助</span></li>
            <li>
                <img alt="系统管理" src="http://erp.mygjp.com/Images/menuImg/系统管理_a.png" href="ROSMain.gspx" />
                <span>系统管理</span></li>
            <li>
                <img alt="基本信息" src="http://erp.mygjp.com/Images/menuImg/基本信息_a.png" name="5" />
                <span>基本信息</span></li>
            <li>
                <img alt="进销存" src="http://erp.mygjp.com/Images/menuImg/进销存管理_正常.png" name="6" />
                <span>进销存</span></li>
            <li>
                <img alt="网店管理" src="http://erp.mygjp.com/Images/menuImg/网店管理_正常.png" name="7" />
                <span>网店管理</span></li>
            <li>
                <img alt="网店绩效" src="http://erp.mygjp.com/Images/menuImg/网店绩效管理_正常.png" name="8" />
                <span>网店绩效</span></li>
            <li>
                <img alt="网店CRM" src="http://erp.mygjp.com/Images/menuImg/E-CRM管理_正常.png" name="9" />
                <span>网店CRM</span></li>
            <li>
                <img alt="分销管理后台" src="http://erp.mygjp.com/Images/menuImg/在线订货.png" name="10" />
                <span>分销管理后台</span></li>
            <li>
                <img alt="服务中心" src="http://erp.mygjp.com/Images/menuImg/服务中心.png" href="ROSMain.gspx" />
                <span>服务中心</span></li>
        </ul>
    </div>
</div>

JinxiaocunApp/Views/MyTart/MenuPartial.cshtml
<div id="@ViewBag.divid" class="tabsCla">
    <ul>
        @*<li><a href="#tabs-@ViewBag.divid">@ViewBag.name</a><span class="ui-icon ui-icon-close" role="presentation">Remove Tab</span></li>*@
        @if (ViewBag.MenuM!=null)
        {
            foreach (JinxiaocunApp.Models.BPartMenu m in ViewBag.MenuM)
            {
                if (m.BOpenModel != null && m.BOpenModel.Trim().Equals("admin"))
                {
                    if (Request.IsAuthenticated && User.IsInRole("admin"))
                    {

                    }
                    else
                    {
                        continue;
                    }
                }
                else
                {

                }
                <li><a href="@m.BLinkUrl.ToLower()">@m.BOtherName</a>@*<span class="ui-icon ui-icon-close" role="presentation">Remove Tab</span>*@</li>
            }
        }
    </ul>
    @*<div id="tabs-@ViewBag.divid">
        <p>建设中。。。</p>
    </div>*@
</div>
<script>
    $(function () {
        $("#@ViewBag.divid").tabs({
            beforeLoad: function (event, ui) {
                ui.jqXHR.error(function () {
                    ui.panel.html(
            "不能加载此项，请确认你有足够的权限. " +
            "如仍由问题联系管理员");
                });
            }
        }).delegate("span.ui-icon-close", "click", function () {
            var panelId = $(this).closest("li").remove().attr("aria-controls");
            $("#" + panelId).remove();
            //this.tabs("refresh");
        });
        @*$('#@ViewBag.divid').load("/Bemp_GongGao/Index");*@
    });


</script>

JinxiaocunApp/Views/MyTart/PaginationPartial.cshtml
<div id="@ViewBag.divid"></div>

@*<p id="result"></p>*@
<script>
$(function() {

    $("#@ViewBag.divid").jui_pagination({
			currentPage:1 ,
			visiblePageLinks: 5,
			totalPages: @ViewBag.TotalPage,
			containerClass: 'container1',

			useSlider: true,
			sliderInsidePane: true,
			sliderClass: 'slider1',
            showNavButtons:true,
			disableSelectionNavPane: true,

			navRowsPerPageClass: 'rows-per-page1  ui-state-default ui-corner-all',
			navGoToPageClass: 'goto-page1 ui-state-default ui-corner-all',

			onChangePage: function(event, page_num) {
				if(isNaN(page_num) || page_num <= 0) {
					alert('Invalid page' + ' (' + page_num + ')');
				} else {
//					$("#result").html('Page changed to: ' + page_num+' '+(page_num%5+1));
                    $("#@ViewBag.tbodyPages").load('@Url.Action("Pages",ViewBag.ControllerName)/'+page_num,new function(){
                       
                    });
                  
                    
				}
			},
			onSetRowsPerPage: function(event, rpp) {
				if(isNaN(rpp) || rpp <= 0) {
					alert('Invalid rows per page' + ' (' + rpp + ')');
				} else {
					alert('rows per page successfully changed' + ' (' + rpp + ')');
					$(this).jui_pagination({
						rowsPerPage: rpp
					})
				}
			},
			onDisplay: function() {
				var showRowsInfo = $(this).jui_pagination('getOption', 'showRowsInfo');
				if(showRowsInfo) {
					var prefix = $(this).jui_pagination('getOption', 'nav_rows_info_id_prefix');
					$("#" + prefix + $(this).attr("id")).text('Total rows: XXX');
				}
			}
		});

//		$("#result").html('Current page is:' + $("#@ViewBag.divid").jui_pagination('getOption', 'currentPage'));

});

</script>

JinxiaocunApp/Views/MyTart/Part1.cshtml
 @*@Html.Action("Menu", "BPartMenu", new { id = -1, tagetdiv = "part1ID"})*@
 @Html.Action("MenuPartial", "MyTart", new { id = "part1ID", tabName = "Part1名称",tabid=-1 })


@*<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        <blockquote>
        ASP.NET <abbr title="gggggggg"> gives </abbr>you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <small>刘.锋</small>
        </blockquote>
    </li>

    <li class="two">
        <code>
            aa
            bb
            cc
        </code>
        <pre>
            
            aa
            bb
        </pre>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        <form role="form" class="form-horizontal">
            <div class="form-group">
                <label for="put1" class="col-sm-2 control-label">email:</label>
                <div class="col-sm-4">
                <input type="email" class="form-control " id="put1" placeholder="email" />
                </div>
            </div>
        </form>
    </li>
</ol>
<table class="table-striped table-hover">
    <tr>
        <th class="success">aaaaaaa</th>
        <th>bbbbbbb</th>
    </tr>
    <tr class="danger">
        <td>xiao</td>
        <td>dada</td>
    </tr><tr>
        <td>xiao</td>
        <td>dada</td>
    </tr>
    <tr>
        <td>xiao</td>
        <td>dada</td>
    </tr>
    <tr>
        <td>xiao</td>
        <td>dada</td>
    </tr>

</table>*@

JinxiaocunApp/Views/MyTart/Part2.cshtml
@if (1 == 2)
    { 
        <script type="text/javascript" src="../../Scripts/jquery-2.0.3-vsdoc.js"></script>
    }
    
@Html.Action("Menu", "BPartMenu", new { id = -1, tagetdiv = "thisid"})
<div style=" width:100%; height:100%; display:block; min-height:420px;">
@Html.Action("MenuPartial", "MyTart", new { id="thisid",tabName="这是名称"})
</div>

JinxiaocunApp/Views/MyTart/SystemM.cshtml
@*@Html.Action("Menu", "BPartMenu", new { id = -2, tagetdiv = "systemMid" })*@
<div style=" width:100%; height:100%; display:block; min-height:420px;">
@Html.Action("MenuPartial", "MyTart", new { id="systemMid",tabName="这是名称",tabid=-2})
</div>