JinxiaocunApp/Models/Tender/Tender_TongZhi.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JinxiaocunApp.Models
{
    public class Tender_TongZhi
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TZID { get; set; }

        [Display(Name="标题")]
        [Required]
        public string TitleT { get; set; }

        [Display(Name = "发表日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? CreateDateT { get; set; }

        [Display(Name="内容")]
        public string ContentT { get; set; }

        [Display(Name="文件上传")]
        public string CustFile { get; set; }

        public string CustName { get; set; }
    }
}

JinxiaocunApp/Controllers/MyTartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JinxiaocunApp.Filters;

namespace JinxiaocunApp.Controllers
{
    
    public class MyTartController : Controller
    {
        //
        // GET: /MyTart/

        JinxiaocunApp.Models.JinxiaocunAppContext db = new Models.JinxiaocunAppContext();
        [MultipleResponseFormats]
        public ActionResult Index()
        {
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult Error(string err="错误",string Act="index",string Con="Home")
        {
            ViewBag.err = err;
            ViewBag.Act = Act;
            ViewBag.Con = Con;
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult MenuPartial(string id="id",string tabName="新Tab",int tabid=-99)
        {
            ViewBag.divid = id;
            ViewBag.name = tabName;
            if(tabid!=-99)
            ViewBag.MenuM = db.BPartMenus.Where(m => m.BParentID == tabid).ToList();
            return View();
        }

        [MultipleResponseFormats]
        public ActionResult PaginationPartial(string id = "Paginationid", int TotalPage = 10, string tbodyPages = "", string ControllerName="")
        {
            ViewBag.divid = id;
            ViewBag.TotalPage = TotalPage==0?1:TotalPage;
            ViewBag.tbodyPages = tbodyPages;
            ViewBag.ControllerName = ControllerName;
            return View();
        }

        public ActionResult Part1()
        {
            return PartialView();
        }

        public ActionResult Part2()
        {
            return PartialView();
        }

        public ActionResult SystemM()
        {
            return PartialView();
        }

        [MultipleResponseFormats]
        public ActionResult IndexM()
        {
            return View();
        }

        public ActionResult Part3()
        {
            return Content("建设中...");
        }
        public ActionResult Part4()
        {
            return Content("Part4"+Request["aa"]+Request["bb"]);
        }
        public ActionResult Part5()
        {
            return Content("<div>Part5</div>");
        }
    }
}

JinxiaocunApp/Controllers/Tender/Tender_TongZhiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JinxiaocunApp.Models;
using JinxiaocunApp.Filters;
using System.IO;

namespace JinxiaocunApp.Controllers.Tender
{
    public class Tender_TongZhiController : Controller
    {
        private JinxiaocunAppContext db = new JinxiaocunAppContext();
        private int PageSize = 15;
        //
        // GET: /Tender_TongZhi/

        [MultipleResponseFormats]
        public ActionResult Index(string id = "")
        {
            ViewBag.SuperRef = id;
            ViewBag.PageDiv = Guid.NewGuid().ToString();
            ViewBag.Pagination = Guid.NewGuid().ToString();



            if (ViewBag.PageSize == null)
            {
                ViewBag.PageSize = PageSize;
                ViewBag.CurrentPage = 1;
                ViewBag.TotalRecord = db.Tender_TongZhi.Count();
                ViewBag.TotalPage = Math.Ceiling(ViewBag.TotalRecord / (double)ViewBag.PageSize);

            }
            return View(db.Tender_TongZhi.Where(m => m.TZID == 0));
        }

        public ActionResult Pages(int id = 1, string SuperRef = "")
        {
            //ViewBag.ProType = db.Tender_ProjectTypes.ToList();
            ViewBag.SuperRef = SuperRef;
            ViewBag.CurrentPage = id;

            //ViewBag.tid = id + "  " + new Random().Next();
            return PartialView(db.Tender_TongZhi.OrderByDescending(m => m.TZID).Skip((id - 1) * PageSize).Take(PageSize).ToList());
            //return PartialView(db.BDepartments.ToList());
        }

        [MultipleResponseFormats]
        public ActionResult IndexTop(int id=0)
        {
            if(id>0)
            {
                return View(db.Tender_TongZhi.OrderByDescending(m => m.CreateDateT).ToList());
            }
            return View(db.Tender_TongZhi.OrderByDescending(m => m.CreateDateT).Take(5).ToList());
        }

        [MultipleResponseFormats]
        public ActionResult MoreIndex(int id = 0)
        {
            
                return View(db.Tender_TongZhi.OrderByDescending(m => m.CreateDateT).ToList());
            
        }
        //
        // GET: /Tender_TongZhi/Details/5

        [MultipleResponseFormats]
        public ActionResult Details(int id = 0)
        {
            Tender_TongZhi tender_tongzhi = db.Tender_TongZhi.Find(id);
            if (tender_tongzhi == null)
            {
                return HttpNotFound();
            }
            return View(tender_tongzhi);
        }

        //
        // GET: /Tender_TongZhi/Create

        [MultipleResponseFormats]
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tender_TongZhi/Create

        [HttpPost]
        //[ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize(Roles = "admin")]
        public ActionResult Create(Tender_TongZhi custf, HttpPostedFileBase[] fileToUpload,int id=0)
        {
            //if (ModelState.IsValid)
            //{
            //    tender_tongzhi.CreateDateT = DateTime.Now;
            //    db.Tender_TongZhi.Add(tender_tongzhi);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //return View(tender_tongzhi);
            if (id == 3)
                return Content("");

            HttpPostedFileBase file = null;
            if (fileToUpload != null)
                file = fileToUpload[0];
            if (file != null && !String.IsNullOrEmpty(file.FileName))
            {
                custf.CustFile = DateTime.Now.ToString("yyyyMMdd") + Guid.NewGuid().ToString("N");
                Directory.CreateDirectory(Path.Combine(System.Web.Configuration.WebConfigurationManager.AppSettings["AttachmentRootPath"], (custf.CustFile.Substring(0, 4) + @"\" + custf.CustFile.Substring(4, 4) + @"\")));
                file.SaveAs(Path.Combine(System.Web.Configuration.WebConfigurationManager.AppSettings["AttachmentRootPath"], (custf.CustFile.Substring(0, 4) + @"\" + custf.CustFile.Substring(4, 4) + @"\" + custf.CustFile.Substring(8))));
                GenericDataAccess.UpdateBySql("Insert into YZAppAttachment(FileID,Name,Ext,Size,OwnerAccount) values(@FileID,@Name,@Ext,@Size,@OwnerAccount)", new string[,] { 
                    { "@FileID",custf.CustFile,"DbType.String",null },
                    { "@Name",Path.GetFileName(file.FileName),"DbType.String",null },
                    { "@Ext",Path.GetExtension(file.FileName),"DbType.String",null },
                    { "@Size",file.ContentLength.ToString(),"DbType.Int32",null },
                    { "@OwnerAccount","0","DbType.String",null } });
                custf.CustName = Path.GetFileName(file.FileName);
                
            }

            custf.CreateDateT = System.DateTime.Now;

            db.Tender_TongZhi.Add(custf);
            db.SaveChanges();
            //string fPath = @"D://myupload/" + file.FileName;
            //file.SaveAs(fPath);
            //string custT="nul";
            //if(custf!=null)
            //{
            //    custT = custf.CustText;
            //}
            return Content("保存成功");
        }

        //
        // GET: /Tender_TongZhi/Edit/5

        [MultipleResponseFormats]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id = 0)
        {
            Tender_TongZhi tender_tongzhi = db.Tender_TongZhi.Find(id);
            if (tender_tongzhi == null)
            {
                return HttpNotFound();
            }
            return View(tender_tongzhi);
        }

        //
        // POST: /Tender_TongZhi/Edit/5

        [HttpPost]
        [MultipleResponseFormats]
        [ValidateInput(false)]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(Tender_TongZhi tender_tongzhi)
        {
            if (ModelState.IsValid)
            {
                Tender_TongZhi ttz = db.Tender_TongZhi.Find(tender_tongzhi.TZID);
                //tender_tongzhi.CreateDateT = ttz.CreateDateT;
                //tender_tongzhi.CustFile = ttz.CustFile;
                //tender_tongzhi.CustName = ttz.CustName;
                ttz.TitleT = tender_tongzhi.TitleT;
                ttz.ContentT = tender_tongzhi.ContentT;
                db.Entry(ttz).State = EntityState.Modified;
                db.SaveChanges();
                return Content("修改成功!");
            }
            return Content("修改失败!");
        }

        //
        // GET: /Tender_TongZhi/Delete/5

        [MultipleResponseFormats]
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Tender_TongZhi tender_tongzhi = db.Tender_TongZhi.Find(id);
            if (tender_tongzhi == null)
            {
                return HttpNotFound();
            }
            return View(tender_tongzhi);
        }

        //
        // POST: /Tender_TongZhi/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tender_TongZhi tender_tongzhi = db.Tender_TongZhi.Find(id);
            db.Tender_TongZhi.Remove(tender_tongzhi);
            db.SaveChanges();
            return RedirectToAction("index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

JinxiaocunApp/Views/Tender_TongZhi/Create.cshtml
@model JinxiaocunApp.Models.Tender_TongZhi

@{
    ViewBag.Title = "Create";
}
@*<script type="text/javascript" src="@Url.Content("~/Scripts/ckeditor/ckeditor.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/ckeditor/adapters/jquery.js")"></script>*@

<div class="panel panel-info" >
    @*<div class="panel-headings">
        <span>
            <img src="~/Images/news/ak15.jpg"></img>
        </span>
        <span>
            <strong>通知公告-新建</strong>
        </span>
    </div>*@
    <div class="panel-body">
        @using (Ajax.BeginForm("Create", "Tender_TongZhi", new { id = 3 }, new AjaxOptions { UpdateTargetId = "formDiv2", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnSuccess = "fileUpload", OnComplete = "onReloadClose('tender_tongzhi/index','formDiv1')" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Tender_TongZhi</legend>

                <div class="editor-label">
                    @Html.LabelFor(model => model.TitleT)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.TitleT, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TitleT)
                </div>

                @*<div class="editor-label">
                        @Html.LabelFor(model => model.CreateDateT)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.CreateDateT)
                        @Html.ValidationMessageFor(model => model.CreateDateT)
                    </div>*@

                <div class="editor-label">
                    @Html.LabelFor(model => model.ContentT)
                </div>
                <div class="editor-field">

                    @Html.TextAreaFor(model => model.ContentT)

                    @Html.ValidationMessageFor(model => model.ContentT)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.CustFile)
                </div>
                <div class="editor-field">

                    <input type="file" name="fileToUpload" id="fileToUpload" onchange="fileSelected();" />
                    @*<button type="button" onclick="fileUpload();" class="btn btn-warning">上传</button>*@
                    <span id="fileName"></span>&nbsp;
                    <span id="fileSize"></span>&nbsp;
                    <span id="fileType"></span>
                    <div id="progressNumber"></div>
                    <div id="progressNumberT"></div>
                    @Html.ValidationMessageFor(model => model.CustFile)
                </div>
                <p>
                    <input type="submit" value="创建" class="btn btn-danger" />
                    @*|
                    @Html.ActionLink("返回列表", "Index", null, new { style = "font-size:14px;" })*@
                </p>
                <div style="float:left; overflow:hidden; width:200px; height:1px;">
                    <div style="margin-left:9999px">
                        @Html.TextBoxFor(model => model.CustFile, new { style = "width:1px;", @readonly = "readonly" })
                    </div>
                </div>

            </fieldset>
        }
        </div>
    </div>
        
        @*@section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }*@

        
        <script>
            $.getScript("/Scripts/jquery.validate.unobtrusive.js");

            function fileSelected() {
                var file = document.getElementById('fileToUpload').files[0];
                if (file) {
                    var fileSize = 0;
                    if (file.size > 1024 * 1024)
                        fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
                    else
                        fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';

                    document.getElementById('fileName').innerHTML = '名称: ' + file.name;
                    document.getElementById('fileSize').innerHTML = '大小: ' + fileSize;
                    document.getElementById('fileType').innerHTML = '类型: ' + file.type;
                }
            }

            function fileUpload() {
                var filet = document.getElementById('fileToUpload').files[0];
                //if (filet[0])
                //{

                //} else
                //{
                //    return;
                //}
                    
                var fd = new FormData();

                fd.append("fileToUpload", document.getElementById('fileToUpload').files[0]);
                fd.append("TitleT", document.getElementById("TitleT").value);
                fd.append("ContentT", document.getElementById("ContentT").value);
                //fd.append("Gid", document.getElementById("Gid").value);

                var xhr = new XMLHttpRequest();

                xhr.upload.addEventListener("progress", uploadProgress, false);

                xhr.addEventListener("load", uploadComplete, false);

                xhr.addEventListener("error", uploadFailed, false);

                xhr.addEventListener("abort", uploadCanceled, false);

                xhr.open("POST", "/tender_tongzhi/Create");

                xhr.send(fd);
            }
            function uploadProgress(evt) {

                if (evt.lengthComputable) {

                    var percentComplete = Math.round(evt.loaded * 100 / evt.total);
                    $("#progressNumber").progressbar({
                        value: percentComplete
                    });
                    document.getElementById('progressNumberT').innerHTML = percentComplete.toString() + '%';

                }

                else {

                    document.getElementById('progressNumber').innerHTML = 'unable to compute';

                }

            }



            function uploadComplete(evt) {

                /* This event is raised when the server send back a response */
                $("#progressNumber").progressbar({
                    value: 100
                });
                document.getElementById('progressNumberT').innerHTML = '100%';
                @*$("#custFile_@Model.Gid").load("/Tender_ModelCustomer1/IndexFile/@Model.Gid");*@

                document.getElementById('fileName').innerHTML = '';
                document.getElementById('fileSize').innerHTML = '';
                document.getElementById('fileType').innerHTML = '';
                document.getElementById("TitleT").value = "";
                document.getElementById("ContentT").value = "";
                document.getElementById("fileToUpload").value = "";
                alert(evt.target.responseText);

            }



            function uploadFailed(evt) {

                alert("There was an error attempting to upload the file.");

            }



            function uploadCanceled(evt) {

                alert("The upload has been canceled by the user or the browser dropped the connection.");

            }
            
            $(function () {



                //if( CKEDITOR.instances['ContentT'] ){
                //    CKEDITOR.remove(CKEDITOR.instances['ContentT']);
                //}



                //if( editor ){

                //    editor.destroy();

                //    editor = null;

                //}

                //$.fn.editor = function () {
                //var ic = 0;
                //for (o in CKEDITOR.instances) {
                //    alert(ic++);
                //        CKEDITOR.remove(CKEDITOR.instances[o]);
                //    }

                //$("#ContentT").ckeditor();
                //}

                //var inst = CKEDITOR.replace('ContentT');
                //if (window.inst) {
                //    alert("remove");
                //    window.inst.destroy();

                //}

                
                //if (window.ckeOBJ)
                //{
                //    alert("cunzai");

                //}
                //else {
                //    alert("不存在");
                //    window.ckeOBJ = CKEDITOR.instances('ContentT');
                //}



            });
        </script>

JinxiaocunApp/Views/Tender_TongZhi/Delete.cshtml
@model JinxiaocunApp.Models.Tender_TongZhi

@{
    ViewBag.Title = "Delete";
}

<h3 class="text-danger">确定要删除吗?</h3>
<div class="row text-center  h3">
    <b>@Model.TitleT</b>
</div>
<div class="row text-center" style="background-color: rgb(240, 240, 240); height: 30px; padding-top: 5px; padding-right: 10px; border-bottom: 1px solid rgb(204, 204, 204);">
    <div class="pull-right">
        发表日期：@Html.DisplayFor(model => model.CreateDateT)
    </div>
</div>
<div class="row" style="padding-left:50px; background-color:rgb(249,249,249);">
    @Html.Raw(Model.ContentT)
</div>
@using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "formDiv1", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnSuccess = "onReloadClose('tender_tongzhi/index','formDiv1')" ,OnFailure="alert('nosuccess..')"}))
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="删除" class="btn btn-danger" /> 
        @*|
        @Html.ActionLink("返回列表", "Index")*@
    </p>
}

JinxiaocunApp/Views/Tender_TongZhi/Details.cshtml
@model JinxiaocunApp.Models.Tender_TongZhi

@{
    ViewBag.Title = "Details";
}


<div class="row text-center  h3">
    <b>@Model.TitleT</b>
</div>
<div class="row text-center" style="background-color: rgb(240, 240, 240); height: 30px; padding-top: 5px; padding-right: 10px; border-bottom: 1px solid rgb(204, 204, 204);">
    <div class="pull-right" >
        发表日期：@Html.DisplayFor(model => model.CreateDateT)
    </div>
</div>

    @if (!string.IsNullOrEmpty(Model.CustFile))
    {
            <div class="row pull-right" style="height:30px;">
            附件：<a style="color: #428BCA;" href="javascript:void(0);" onclick="downt('@Model.CustFile')">@Model.CustName</a>
        </div>
    }
    else
    {
        
    }

<div class="row" style="padding-left:50px; background-color:rgb(249,249,249);">
    @Html.Raw(Model.ContentT)
</div>
@*<fieldset>
    <legend>Tender_TongZhi</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TitleT)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TitleT)
    </div>

    <div class="display-label">
         
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreateDateT)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContentT)
    </div>
    <div >
    
    </div>
</fieldset>

<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.TZID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

JinxiaocunApp/Views/Tender_TongZhi/Edit.cshtml
@model JinxiaocunApp.Models.Tender_TongZhi

@{
    ViewBag.Title = "Edit";
}

<div class="panel panel-info">
    @*<div class="panel-headings">
        <span>
            <img src="~/Images/news/ak15.jpg"></img>
        </span>
        <span>
            <strong>通知公告-编辑</strong>
        </span>
    </div>*@
    <div class="panel-body">
        @using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "formDiv1", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnSuccess = "onReloadClose('tender_tongzhi/index/','formDiv1')" }))
        {
            @*@Html.AntiForgeryToken()*@
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Tender_TongZhi</legend>

                @Html.HiddenFor(model => model.TZID)

                <div class="editor-label">
                    @Html.LabelFor(model => model.TitleT)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.TitleT, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TitleT)
                </div>

                <div class="editor-label">
                    
                </div>
                <div class="editor-field">
                    @Html.HiddenFor(model => model.CreateDateT)
                   
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.ContentT)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.ContentT)
                    @Html.ValidationMessageFor(model => model.ContentT)
                </div>

                <p>
                    <input type="submit" value="保存" class="btn btn-danger"/>
                    @*|
                    @Html.ActionLink("返回列表", "Index")*@
                </p>
            </fieldset>
        }

        
        </div>
    </div>
 <script>
    $.getScript("/Scripts/jquery.validate.unobtrusive.js");
</script>
@*<script>
    $(function () {
        var cked1 = CKEDITOR.replace('ContentT');
       
    });
</script>*@

JinxiaocunApp/Views/Tender_TongZhi/Index.cshtml
@model IEnumerable<JinxiaocunApp.Models.Tender_TongZhi>

@{
    ViewBag.Title = "Index";
}

<p>
    @Ajax.ActionLink("新建", "Create", null, new AjaxOptions { UpdateTargetId = "formDiv1", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showDIV('formDiv1','通知公告-新建',1100,600)",OnComplete="upecreate" }, new { @class = "btn btn-info" })
    @*@Html.ActionLink("新建", "Create", "Tender_TongZhi", new { @class="btn btn-info"})*@
</p>
<table class="table-striped table-hover table-bordered" width="100%">
    <tr class="alert-info">
        <th>
            @Html.DisplayNameFor(model => model.TitleT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDateT)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ContentT)
        </th>*@
        <th></th>
    </tr>
    <tbody id="@ViewBag.PageDiv">
        @Html.Action("Pages", "Tender_TongZhi", new { SuperRef = ViewBag.SuperRef })
        </tbody>
</table>
@Html.Action("PaginationPartial", "MyTart", new { id = ViewBag.Pagination, TotalPage = ViewBag.TotalPage, tbodyPages = ViewBag.PageDiv, ControllerName = "Tender_TongZhi" })
<script>
    var cedi;
    function upecreate()
    {
        @*$.getScript("@Url.Content("~/Scripts/ckeditor/ckeditor.js")", function () {*@
            //alert('jin');
            
            //if (cedi) {
            //    alert('jin1');
            //    cedi.destroy();
            //    alert('jin2');
            //}
        //cedi = CKEDITOR.replace('ContentT');

        setTimeout("fffun()",1000);
        //})
                
    }
    function fffun()
    {
        CKEDITOR.replace('ContentT');
    }
</script>

JinxiaocunApp/Views/Tender_TongZhi/IndexTop.cshtml
@model IEnumerable<JinxiaocunApp.Models.Tender_TongZhi>

@{
    ViewBag.Title = "Index";
}

<table >

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @*@Html.DisplayFor(modelItem => item.TitleT)*@
                <div style=" max-width: 180px; overflow: hidden; text-overflow: ellipsis; float: left;">

                    <nobr>
                        <img src='@Url.Content("Images/news/ak13.jpg")' />

                        @Ajax.ActionLink(item.TitleT, "Details", new { id = item.TZID }, new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showW('通知公告-查看',1100,500)" })
                    </nobr>
                </div>
            </td>
            <td style="width:80px">
                @Html.DisplayFor(modelItem => item.CreateDateT)
            </td>
           
            
        </tr>
    }

</table>

JinxiaocunApp/Views/Tender_TongZhi/MoreIndex.cshtml
@model IEnumerable<JinxiaocunApp.Models.Tender_TongZhi>

@{
    ViewBag.Title = "Index";
}
<div class="panel panel-info" style="text-align:center">
    <div class="panel-headings">
        <span>
            <img src="~/Images/news/ak15.jpg"></img>
        </span>
        <span>
            <strong>通知公告</strong>
        </span>
    </div>
    <div class="panel-body">
        <table class="table-striped table-hover table-bordered" width="100%">
            @*<tr class="alert-info">
                <th>
                    @Html.DisplayNameFor(model => model.TitleT)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreateDateT)
                </th>

            </tr>*@
            @foreach (var item in Model)
    {
    <tr>
        <td>
            @*@Html.DisplayFor(modelItem => item.TitleT)*@
            <div style=" max-width: 180px; overflow: hidden; text-overflow: ellipsis; float: left;">

                <nobr>
                    <img src='@Url.Content("Images/news/ak13.jpg")' />

                    @Ajax.ActionLink(item.TitleT, "Details", new { id = item.TZID }, new AjaxOptions { UpdateTargetId = "formDiv", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showW('通知公告-查看',1100,500)" })
                </nobr>
            </div>
        </td>
        <td style="width:80px">
            @Html.DisplayFor(modelItem => item.CreateDateT)
        </td>


    </tr>
    }

        </table>
</div>
</div>

JinxiaocunApp/Views/Tender_TongZhi/Pages.cshtml
@model IEnumerable<JinxiaocunApp.Models.Tender_TongZhi>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TitleT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDateT)
        </td>
        @*<td>
                @Html.DisplayFor(modelItem => item.ContentT)
            </td>*@
        <td>
            @Ajax.ActionLink("编辑", "Edit", "Tender_TongZhi", new { id = item.TZID }, new AjaxOptions { UpdateTargetId = "formDiv1", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showDIV('formDiv1','通知公告-修改',1100,600)", OnComplete = "upecreate" })
            @*@Html.ActionLink("编辑", "Edit", new { id = item.TZID })*@ |
            @*@Html.ActionLink("详情", "Details", new { id = item.TZID }) |*@
            @Ajax.ActionLink("详情", "Details", "Tender_TongZhi", new { id = item.TZID }, new AjaxOptions { UpdateTargetId = "formDiv1", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showDIV('formDiv1','通知公告-查看',1100,600)" })|
            @Ajax.ActionLink("删除", "Delete", "Tender_TongZhi", new { id = item.TZID }, new AjaxOptions { UpdateTargetId = "formDiv1", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showDIV('formDiv1','通知公告-删除',1100,600)" })
            @*@Html.ActionLink("删除", "Delete", new { id = item.TZID })*@
        </td>
    </tr>
}