JinxiaocunApp/Models/Tender/Tender_ModelCustomer1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JinxiaocunApp.Models
{
    public class Tender_ModelCustomer1
    {
        [Key][DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MID { get; set; }

        [Display(Name="第一轮报价")]
        public decimal PriceOne { get; set; }

        [Display(Name = "第二轮报价")]
        public decimal PriceTwo { get; set; }

        
        [Display(Name = "本次报价")]
        [Required]
        [Range(0.01, 999999999, ErrorMessage = "报价必须大于{1}")]
        public decimal PriceThree { get; set; }

        [Display(Name = "价格单位")]
        public string PriceUnit { get; set; }

        [Display(Name = "竞标供应商名称")]
        public string UserName { get; set; }

        [Display(Name = "联系人")]
        public string LinkMan { get; set; }

        [Display(Name = "联系方式")]
        public string LinkType { get; set; }

        public int EmpGonggaoID { get; set; }

        [ForeignKey("EmpGonggaoID")]
        public Bemp_GongGao bemp_Gonggao { get; set; }
    }

    public class Tender_CustomerFiles
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TID { get; set; }
        [Display(Name = "报价清单")]
        [Required]
        public string CustText { get; set; }

        [Display(Name = "文件上传")]
        public string CustFile { get; set; }

        public int? Gid { get; set; }
    }
}

JinxiaocunApp/Controllers/Tender/Tender_ModelCustomer1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JinxiaocunApp.Models;
using JinxiaocunApp.Filters;
using System.IO;

namespace JinxiaocunApp.Controllers.Tender
{
    public class Tender_ModelCustomer1Controller : Controller
    {
        private JinxiaocunAppContext db = new JinxiaocunAppContext();

        public bool isSmall = true;
        //
        // GET: /Tender_ModelCustomer1/
        [MultipleResponseFormats]
        public ActionResult Index(int id=0)
        {
            isSmall = isSmallByid(id);
            var tender_mcust = db.Tender_ModelCustomer1.Include(t => t.bemp_Gonggao).Where(mc => mc.bemp_Gonggao.GongGaoId == id);
            //第一次加载 生成客户初始数据
            if (tender_mcust.Count() <= 0)
            {
                List<Bemp_GongGao> list = db.Bemp_GongGaos.Include(b => b.bemplyees).Where(m => m.GongGaoId == id&&m.IsPassShen!=null&&m.IsPassShen==true).ToList();
                if (list.Count > 0)
                {
                    //List<Tender_ModelCustomer1> li = new List<Tender_ModelCustomer1>();
                    lock (this)
                    {
                        foreach (Bemp_GongGao bemp in list)
                        {
                            Tender_ModelCustomer1 cust = new Tender_ModelCustomer1();
                            cust.UserName = bemp.bemplyees.NumberEmp;
                            cust.LinkMan = bemp.bemplyees.LinkMan;
                            cust.LinkType = bemp.bemplyees.LinkType;
                            cust.EmpGonggaoID = bemp.BGid;
                            cust.PriceOne = 0;
                            cust.PriceTwo = 0;
                            cust.PriceThree = 0;
                            if (db.Tender_ModelCustomer1.Where(m => m.EmpGonggaoID == bemp.BGid).Count() <= 0)
                                db.Tender_ModelCustomer1.Add(cust);
                            //li.Add(cust);
                            db.Configuration.ValidateOnSaveEnabled = false;
                            db.SaveChanges();
                            db.Configuration.ValidateOnSaveEnabled = true;
                        }
                    }
                    


                }
            }

            
            //找每轮最低价
            //tender_mcust = db.Tender_ModelCustomer1.Include(t => t.bemp_Gonggao).Where(mc => mc.bemp_Gonggao.GongGaoId == id);

            ViewBag.PriceD1 = ViewBag.PriceD2=ViewBag.PriceD3 = 0;

            tender_mcust = db.Tender_ModelCustomer1.Include(t => t.bemp_Gonggao).Where(mc => mc.bemp_Gonggao.GongGaoId == id&&mc.PriceOne>0);
            if(tender_mcust.Count()>0)
            {
                if(isSmall)
                {
                    ViewBag.PriceD1 = tender_mcust.Min(m => m.PriceOne);
                }else
                {
                    ViewBag.PriceD1 = tender_mcust.Max(m => m.PriceOne);
                }
            }
            

            tender_mcust = db.Tender_ModelCustomer1.Include(t => t.bemp_Gonggao).Where(mc => mc.bemp_Gonggao.GongGaoId == id && mc.PriceTwo > 0);
            if (tender_mcust.Count() > 0)
            {
                if(isSmall)
                {
                    ViewBag.PriceD2 = tender_mcust.Min(m => m.PriceTwo);
                }else
                {
                    ViewBag.PriceD2 = tender_mcust.Max(m => m.PriceTwo);
                }
            }
            

            tender_mcust = db.Tender_ModelCustomer1.Include(t => t.bemp_Gonggao).Where(mc => mc.bemp_Gonggao.GongGaoId == id && mc.PriceThree > 0);
            if (tender_mcust.Count() > 0)
            {
                if(isSmall)
                {
                    ViewBag.PriceD3 = tender_mcust.Min(m => m.PriceThree);
                }else
                {
                    ViewBag.PriceD3 = tender_mcust.Max(m => m.PriceThree);
                }
            }
            

           
            //重新取数
            tender_mcust = db.Tender_ModelCustomer1.Include(t => t.bemp_Gonggao).Where(mc => mc.bemp_Gonggao.GongGaoId == id);

            if(isSmall)
            {
                //循环找最低价
                foreach (Tender_ModelCustomer1 custVar in tender_mcust.ToList<Tender_ModelCustomer1>())
                {
                    Bemp_GongGao bgong = db.Bemp_GongGaos.Find(custVar.EmpGonggaoID);
                    var v1 = custVar.PriceOne != 0 ? custVar.PriceOne : 9999999999;
                    var v2 = custVar.PriceTwo != 0 ? custVar.PriceTwo : 9999999999;
                    var v3 = custVar.PriceThree != 0 ? custVar.PriceThree : 9999999999;
                    bgong.LostPrice = (v1 < v2 ? v1 : v2) < v3 ? (v1 < v2 ? v1 : v2) : v3;
                    if (bgong.LostPrice != 9999999999)
                    {

                        db.Entry(bgong).State = EntityState.Modified;
                        db.Configuration.ValidateOnSaveEnabled = false;
                        db.SaveChanges();
                        db.Configuration.ValidateOnSaveEnabled = true;
                    }
                    else
                    {
                        bgong.LostPrice = 0;
                    }

                }
            }else
            {
                //循环找最高价
                foreach (Tender_ModelCustomer1 custVar in tender_mcust.ToList<Tender_ModelCustomer1>())
                {
                    Bemp_GongGao bgong = db.Bemp_GongGaos.Find(custVar.EmpGonggaoID);
                    var v1 = custVar.PriceOne;
                    var v2 = custVar.PriceTwo;
                    var v3 = custVar.PriceThree;
                    bgong.LostPrice = (v1 > v2 ? v1 : v2) > v3 ? (v1 > v2 ? v1 : v2) : v3;
                    if (bgong.LostPrice != 0)
                    {

                        db.Entry(bgong).State = EntityState.Modified;
                        db.Configuration.ValidateOnSaveEnabled = false;
                        db.SaveChanges();
                        db.Configuration.ValidateOnSaveEnabled = true;
                    }
                    else
                    {
                        bgong.LostPrice = 0;
                    }

                }
            }

            ViewBag.IsSmall = isSmall;
            
            return View(tender_mcust);
        }

        //
        // GET: /Tender_ModelCustomer1/Details/5

        public ActionResult Details(int id = 0)
        {
            Tender_ModelCustomer1 tender_modelcustomer1 = db.Tender_ModelCustomer1.Find(id);
            if (tender_modelcustomer1 == null)
            {
                return HttpNotFound();
            }
            return View(tender_modelcustomer1);
        }

        //
        // GET: /Tender_ModelCustomer1/Create

        [MultipleResponseFormats]
        public ActionResult Create(int id=0)
        {
           
            ViewBag.EmpGonggaoID = new SelectList(db.Bemp_GongGaos, "BGid", "BGid");
            if (id != 0)
            {
                
                Bemp_GongGao empGong =null;
                try
                {
                    empGong = db.Bemp_GongGaos.Include(m => m.Tender_GongGaos).Single(m => m.BGid == id && m.IsPassShen != null && m.IsPassShen == true);

                    isSmall = isSmallByid(empGong.GongGaoId);
                    ViewBag.IsSmall = isSmall;
                }catch(Exception ex)
                {
                    return Content("不能投标，您可能审核未通过。");
                }
                
                Tender_ModelManage1 modelM = db.Tender_ModelManage1.Single(m => m.Tid == empGong.GongGaoId);
               
                if(modelM==null)
                { return Content("投标未开始"); }

                TimeSpan tsEnd3 ;
                if(TimeSpan.TryParse(modelM.EndTime3,out tsEnd3))
                {
                    if(tsEnd3<=System.DateTime.Now.TimeOfDay)
                    {
                        return Content("投标已结束");
                    }
                }

                if (modelM.DateToday.Date < System.DateTime.Now.Date)
                {
                    return Content("投标已结束~!");
                }
                if (modelM.DateToday.Date > System.DateTime.Now.Date)
                {
                    return Content("投标未开始~!");
                }
                if (empGong != null)
                {
                    Tender_ModelCustomer1 cust;
                    cust = db.Tender_ModelCustomer1.Include(m=>m.bemp_Gonggao.Tender_GongGaos).Single(m => m.EmpGonggaoID == empGong.BGid);
                    if(cust==null)
                    {
                        return Content("请联系管理");
                        //cust=new Tender_ModelCustomer1();
                        //cust.EmpGonggaoID=id;
                        //cust.PriceUnit = modelM.PriceUnit;
                        //cust.LinkMan=empGong
                        //db.Tender_ModelCustomer1.Add(cust);
                        
                        //db.SaveChanges();
                    }
                    cust.PriceUnit = modelM.PriceUnit;
                    db.Entry(cust).State = EntityState.Modified;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                    db.Configuration.ValidateOnSaveEnabled = true;

                    if ((!string.IsNullOrEmpty(modelM.BeginTime1)) && (!string.IsNullOrEmpty(modelM.EndTime1)) && TimeSpan.Parse(modelM.EndTime1)>=System.DateTime.Now.TimeOfDay)
                    {
                        ViewBag.Lunci = "一 未开始";
                        ViewBag.TimeXia = modelM.BeginTime1;
                        if((TimeSpan.Parse(modelM.BeginTime1) <= System.DateTime.Now.TimeOfDay && System.DateTime.Now.TimeOfDay <= TimeSpan.Parse(modelM.EndTime1)))
                        {
                            //第一轮进行中
                            ViewBag.Lunci = "一";

JinxiaocunApp/Views/Tender_ModelCustomer1/Create.cshtml
@model JinxiaocunApp.Models.Tender_ModelCustomer1

@{
    ViewBag.Title = "供应商投标";
}
@if (1 == 2)
{
    <script type="text/javascript" src="../../Scripts/jquery-2.0.3-vsdoc.js"></script>
}
<h2>供应商投标</h2>

@using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "tender_div_cust", HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnComplete = "tender_cust_Secess" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tender_ModelCustomer1</legend>
        <table class="table-striped table-hover table-bordered" width="100%" style="line-height:26px">
            <tr>
                <td>
                    @Html.LabelFor(model => model.bemp_Gonggao.Tender_GongGaos.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => model.bemp_Gonggao.Tender_GongGaos.Name)
                </td>
                <td>
                    @Html.LabelFor(model=>model.bemp_Gonggao.Tender_GongGaos.BeginDate)
                </td>
                <td>
                    @Html.DisplayFor(model=>model.bemp_Gonggao.Tender_GongGaos.BeginDate)
                </td>
                <td>
                    @Html.LabelFor(model=>model.bemp_Gonggao.Tender_GongGaos.EndDate)
                </td>
                <td width="100px">
                    @Html.DisplayFor(model=>model.bemp_Gonggao.Tender_GongGaos.EndDate)
                </td>
                <td>
                    <label>供应商名称</label>
                </td>
                <td>
                    @User.Identity.Name
                </td>
            </tr>
            <tr>
                <td>
                    <label>本次招标轮次</label>
                </td>
                <td>
                    <input type="text" readonly="readonly" id="LunciLab" name="LunciLab" value="@ViewBag.Lunci" class="form-control" />
                </td>
                <td>
                    <label>离本轮竞标结束还有</label>
                </td>
                <td>
                    
                    <input type="text" readonly="readonly" id="EndTime" name="EndTime" value="@ViewBag.Jieshu" class="form-control" />
                        
                   
                </td>
                <td>
                    @if(ViewBag.IsSmall)
                    {
                        <label>
                        上一轮最低价
                        </label>
                    }else
                    {
                        <label>
                        上一轮最高价
                    </label>
                    }
                    
                </td>
                <td>
                    <input type="text" readonly="readonly" id="PriceShangLow" name="PriceShangLow" value="@ViewBag.ShangDi" class="form-control" />
                </td>
                <td>
                    <label>您上一轮投标价</label>
                </td>
                <td>
                    <input type="text" readonly="readonly" id="PriceShang" name="PriceShang" value="@ViewBag.Shanglun" class="form-control" />
                </td>
               
            </tr>
            <tr>
                <td >
                    <label>下轮开始时间</label>
                </td>
                <td>
                    <input type="text" readonly="readonly" id="TimeXia" name="TimeXia" value="@ViewBag.TimeXia" class="form-control" />
                </td>
                <td>
                    <label>本轮报价</label>
                </td>
                <td width="100px">
                   
                     @Html.TextBoxFor(model => model.PriceThree, new { @class = "form-control" })
               
                </td>
                <td>
                    @Html.DisplayFor(model => model.PriceUnit)
                </td>
                <td>
                    <button type="submit" class="btn btn-info">确认</button>
                </td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td colspan="8">

                    
                </td>
            </tr>
            <tr>
                <td colspan="8" height="60px">
                    @if(ViewBag.IsSmall)
                    {
                        <strong id="dangerStr" class="text-danger" hidden="hidden">
                        请注意，此刻有多家供应商报出了相同的最低价。
                    </strong>
                    }
                    else
                    {
                        <strong id="dangerStr" class="text-danger" hidden="hidden">
                        请注意，此刻有多家供应商报出了相同的最高价。
                    </strong>
                    }
                    
                    @Html.ValidationMessageFor(model => model.PriceThree)
                    @*@Html.ValidationMessageFor(model => model.bemp_Gonggao.PayType)*@
                    @Html.ValidationMessageFor(model => model.bemp_Gonggao.HandDate)
                    <div id="tender_div_cust" class="alert alert-warning alert-dismissable" style="display:none; height:50px;">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.bemp_Gonggao.Tender_GongGaos.PayType)
                </td>
                <td>
                    @Html.DisplayFor(model=>model.bemp_Gonggao.Tender_GongGaos.PayType)
                    @*@Html.TextBoxFor(model => model.bemp_Gonggao.PayType, new { @class = "form-control" })*@
                    
                </td>
                <td>
                    承诺交货周期
                </td>
                <td colspan="2">
                    <div class="input-group date form_datetime" data-date="" data-date-format="yyyy/mm/dd">
                        @Html.TextBoxFor(model => model.bemp_Gonggao.HandDate, new { @class = "form-control", size = "16", @readonly = "" })
                        @*<input class="form-control" size="16" type="text" value="" readonly>*@
                        <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>

                    </div>
                    @*@Html.TextBoxFor(model => model.bemp_Gonggao.HandDate, new { @class = "form-control" })*@
                </td>
                <td colspan="3"></td>
            </tr>
            <tr>
                <td colspan="8" style="background-color:#808080">
                   <strong>报价清单</strong> 
                </td>
            </tr>
            <tr>
                <td colspan="8">
                    <div id="custFile_@Model.EmpGonggaoID">

                    </div>
                </td>
            </tr>
            </table>
        @Ajax.ActionLink("添加-报价清单", "CustFiles", "Tender_ModelCustomer1",new{id=Model.EmpGonggaoID}, new AjaxOptions { UpdateTargetId = "formDiv2", HttpMethod = "Get", InsertionMode = InsertionMode.Replace, OnSuccess = "showDIV('formDiv2','报价清单')" }, new { @class="btn btn-info"})
                @Html.HiddenFor(model=>model.EmpGonggaoID)
        <br />
        <strong style="color:red">价格单位备注:</strong>  我司招标价格单位为元/标，意思是本次投标所涉及的所有标的物不能进行拆分，是本次投标的总价格。
               
    </fieldset>
}
<script>
    function startC() {
        var inc = document.getElementById('incomming');
        var wsImpl = window.WebSocket || window.MozWebSocket;
        //var form = document.getElementById('sendForm');
        //var input = document.getElementById('sendText');

        inc.innerHTML += "connecting to server ..<br/>";

        // create a new websocket and connect
        if (window.ws && window.ws != "undefined") {

        } else {
            window.ws = new wsImpl(svIpc);
        }

        // when data is comming from the server, this metod is called
        ws.onmessage = function (evt) {
            if (inc.innerHTML.length > 500)
            {
                inc.innerHTML = evt.data + '<br/>' + inc.innerHTML.substring(0, 500);
            } else
            {
                inc.innerHTML = evt.data + '<br/>' + inc.innerHTML;
            }
            
            

            if (evt.data.indexOf('reload') >= 0)
            {
                $.ajax({
                    url: "Tender_ModelCustomer1/LoadData/@Model.bemp_Gonggao.BGid",
                    success: function (result) {
                        //alert("ok" + result.Lunci);
                        $("#LunciLab").val(result.Lunci);
                        $("#EndTime").val(result.EndTime);
                        $("#PriceShang").val(result.PriceShang);
                        $("#PriceShangLow").val(result.PriceShangLow);
                        $("#TimeXia").val(result.TimeXia);
                        if (result.StrServ.indexOf("请注意") >= 0)
                        {
                            $("#dangerStr").show(1000);
                        } else
                        {
                            $("#dangerStr").hide(1000);
                        }
                        if (window.ttt) {
                            if (window.ttt == "undefined") {
                                if ($("#LunciLab").val().indexOf("未") >= 0) {
                                    //clearInterval(ttt);
                                    //window.ttt = "undefined"
                                } else {
                                    window.ttt = setInterval("timeBack()", "1000");
                                }
                            } else {
                                if ($("#LunciLab").val().indexOf("未") >= 0) {
                                    clearInterval(ttt);
                                    window.ttt = "undefined"
                                } else {
                                    //window.ttt = setInterval("timeBack()", "1000");
                                }
                            }
                        } else {
                            if ($("#LunciLab").val().indexOf("未") >= 0) {
                                //clearInterval(ttt);
                                //window.ttt = "undefined"
                            } else {
                                window.ttt = setInterval("timeBack()", "1000");
                            }
                        }
                    }
                });
                @*$.post("Tender_ModelCustomer1/LoadData/@Model.bemp_Gonggao.BGid",
                    {},
                    function (datas) {
                        datas.
                    });
                $("#formDiv1")*@
            }
        };

        // when the connection is established, this method is called
        ws.onopen = function () {
            inc.innerHTML += '.. connection open<br/>';
        };

        // when the connection is closed, this method is called
        ws.onclose = function () {
            inc.innerHTML += '.. connection closed<br/>';
            ws = "undefined";
        }

        @*form.addEventListener('submit', function (e) {
            e.preventDefault();
            var val ='@User.Identity.Name >>'+ input.value;
            ws.send(val);
            input.value = "";
        });*@

    }
    $(function () {

        $('.form_datetime').datetimepicker({
            language: 'zh-CN',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minuteStep: 1,
            minView: 2,
            forceParse: 0
        });


        $("#custFile_@Model.EmpGonggaoID").load("/Tender_ModelCustomer1/IndexFile/@Model.EmpGonggaoID");
        //try{
        //    if (typeof (eval(startC)) == "function")
        //    {
        //        startC();
        //    }
        //}catch(e){

        //}
        startC();
        if(window.ttt)
        {
            if(window.ttt=="undefined")
            {
                if ($("#LunciLab").val().indexOf("未") >= 0) {
                    //clearInterval(ttt);
                    //window.ttt = "undefined"
                } else {
                    window.ttt = setInterval("timeBack()", "1000");
                }
            }else
            {
                if ($("#LunciLab").val().indexOf("未") >= 0) {
                    clearInterval(ttt);
                    window.ttt = "undefined"
                } else {
                    //window.ttt = setInterval("timeBack()", "1000");
                }
            }
        }else
        {
            if ($("#LunciLab").val().indexOf("未") >= 0) {
                //clearInterval(ttt);
                //window.ttt = "undefined"
            } else {
                window.ttt = setInterval("timeBack()", "1000");
            }
        }
        //if (typeof (ttt) == "undefined")
        //{
        //    if ($("#LunciLab").val().indexOf("未") >= 0) {

        //    } else {
        //        window.ttt = setInterval("timeBack()", "1000");
        //    }
        //}
        
        ////timeBack();
    })
    
    
    function tender_cust_Secess() {
        $("#tender_div_cust").show("drop", null, 500, callback_cust);
        if ($("#tender_div_cust").text().indexOf("投标完成") >= 0)
        {
            window.ws.send("adreload");
        }
        
    }
    function callback_cust() {
        setTimeout(function () {
            $("#tender_div_cust").removeAttr("style").fadeOut();
        }, 2000);
    }
    $.getScript("/Scripts/jquery.validate.unobtrusive.js");
</script>
@*<form id="sendForm">
    <input id="sendText" placeholder="Text to send" />
</form>*@
<div style="max-height:150px; overflow-y:scroll;">
    <pre id="incomming"></pre>
</div>

JinxiaocunApp/Views/Tender_ModelCustomer1/CustFiles.cshtml
@model JinxiaocunApp.Models.Tender_CustomerFiles

@{
    ViewBag.Title = "CustFiles";
}

<h2>报价清单</h2>
<div id="custtest1"></div>
@using (Ajax.BeginForm("CustFiles", "Tender_ModelCustomer1", new { id = 3 }, new AjaxOptions { UpdateTargetId = "custtest1", HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter, OnComplete = "fileUpload" }))
 {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tender_CustomerFiles</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustText)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustText)
            @Html.ValidationMessageFor(model => model.CustText)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustFile)
        </div>
        <div class="editor-field">
            
            <input type="file" name="fileToUpload" id="fileToUpload" onchange="fileSelected();" />
            @*<button type="button" onclick="fileUpload();" class="btn btn-warning">上传</button>*@
            <span id="fileName"></span>&nbsp;
            <span id="fileSize"></span>&nbsp;
            <span id="fileType"></span>
            <div id="progressNumber"></div>
            <div id="progressNumberT"></div>
            @Html.ValidationMessageFor(model => model.CustFile)
        </div>

        <p>
            <input type="submit" value="保存" class="btn btn-info" />
        </p>
        <div style="float:left; overflow:hidden; width:200px; height:1px;">
            <div style="margin-left:9999px">
                @Html.TextBoxFor(model => model.CustFile, new { style = "width:1px;", @readonly = "readonly" })
                </div>
            </div>
        @Html.HiddenFor(model => model.Gid)
    </fieldset>
 }

<div>
   
</div>

<script>
    $.getScript("/Scripts/jquery.validate.unobtrusive.js");
    function fileSelected()
    {
        var file = document.getElementById('fileToUpload').files[0];
        if (file) {
            var fileSize = 0;
            if (file.size > 1024 * 1024)
                fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
            else
                fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';

            document.getElementById('fileName').innerHTML = '名称: ' + file.name;
            document.getElementById('fileSize').innerHTML = '大小: ' + fileSize;
            document.getElementById('fileType').innerHTML = '类型: ' + file.type;
        }
    }

    function fileUpload()
    {
        //var filet = document.getElementById('fileToUpload').files[0];
        //if (filet == null)
        //    return;
        var fd = new FormData();

        fd.append("fileToUpload", document.getElementById('fileToUpload').files[0]);
        fd.append("CustText", document.getElementById("CustText").value);
        fd.append("Gid", document.getElementById("Gid").value);
        
        var xhr = new XMLHttpRequest();

        xhr.upload.addEventListener("progress", uploadProgress, false);

        xhr.addEventListener("load", uploadComplete, false);

        xhr.addEventListener("error", uploadFailed, false);

        xhr.addEventListener("abort", uploadCanceled, false);

        xhr.open("POST", "/Tender_ModelCustomer1/CustFiles");

        xhr.send(fd);
    }
    function uploadProgress(evt) {

        if (evt.lengthComputable) {

            var percentComplete = Math.round(evt.loaded * 100 / evt.total);
            $("#progressNumber").progressbar({
                value: percentComplete
            });
            document.getElementById('progressNumberT').innerHTML = percentComplete.toString() + '%';

        }

        else {

            document.getElementById('progressNumber').innerHTML = 'unable to compute';

        }

    }



    function uploadComplete(evt) {

        /* This event is raised when the server send back a response */
        $("#progressNumber").progressbar({
            value: 100
        });
        document.getElementById('progressNumberT').innerHTML = '100%';
        $("#custFile_@Model.Gid").load("/Tender_ModelCustomer1/IndexFile/@Model.Gid");

        document.getElementById('fileName').innerHTML = '';
        document.getElementById('fileSize').innerHTML = '';
        document.getElementById('fileType').innerHTML = '';
        document.getElementById("CustText").value = "";
        document.getElementById("fileToUpload").value = "";
        alert(evt.target.responseText);

    }



    function uploadFailed(evt) {

        alert("There was an error attempting to upload the file.");

    }



    function uploadCanceled(evt) {

        alert("The upload has been canceled by the user or the browser dropped the connection.");

    }
</script>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@